services:

  git-manager:
    image: ghcr.io/mborne/git-manager:latest
    build:
      context: .
    environment:
      APP_ENV: ${APP_ENV}
      APP_SECRET: ${APP_SECRET}
    ports:
      - 8000:8000
    volumes:
      - git-manager-data:/var/git-manager
    restart: unless-stopped

volumes:
  git-manager-data:
    name: git-manager-data