parameters:
    env(SECRET): ThisTokenIsNotSoSecretChangeIt
    env(DATA_DIR): '/var/git-manager'

imports:
    - { resource: services.yml }

framework:
    secret: '%env(SECRET)%'
    php_errors:
        log: true
