services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $askPassPath: '%kernel.project_dir%/bin/git-askpass'
            $dataDir: '%env(resolve:GIT_MANAGER_DIR)%'
            $trivyEnabled: '%env(bool:TRIVY_ENABLED)%'
            $trivyConfigPath: '%kernel.project_dir%/config/trivy.yaml'
            $gitleaksEnabled: '%env(bool:GITLEAKS_ENABLED)%'
            $gitleaksConfigPath: '%kernel.project_dir%/config/gitleaks.toml'

    MBO\GitManager\:
        resource: '../src/*'
        exclude:
            - '../src/Kernel.php'

    MBO\GitManager\Filesystem\LocalFilesystemInterface: '@MBO\GitManager\Filesystem\LocalFilesystem'
    MBO\GitManager\Filesystem\FileReaderInterface: '@MBO\GitManager\Filesystem\LocalFileReader'
    MBO\GitManager\Process\ProcessRunnerInterface: '@MBO\GitManager\Process\SymfonyProcessRunner'
