<?php

namespace MBO\GitManager\Git\Checker;

use MBO\GitManager\Entity\Project;
use MBO\GitManager\Filesystem\LocalFilesystem;
use MBO\GitManager\Git\CheckerInterface;
use Psr\Log\LoggerInterface;
use Symfony\Component\Process\Exception\ProcessFailedException;
use Symfony\Component\Process\Process;

/**
 * Perform a scan with gitleaks producing a SARIF report.
 */
final class SecretChecker implements CheckerInterface
{
    private bool $enabled;

    public function __construct(
        bool $gitleaksEnabled,
        private LocalFilesystem $localFilesystem,
        private LoggerInterface $logger,
    ) {
        $this->enabled = $gitleaksEnabled && $this->isAvailable();
    }

    public function getName(): string
    {
        return 'secret';
    }

    public function check(Project $project): mixed
    {
        $repositoryPath = $this->localFilesystem->getGitRepositoryPath($project->getFullName());

        if (!$this->enabled) {
            $this->logger->debug('[{checker}] skipped (disabled)', [
                'checker' => $this->getName(),
                'repository' => $project->getFullName(),
            ]);

            return null;
        }

        $this->logger->debug('[{checker}] run gitleaks scan on repository...', [
            'checker' => $this->getName(),
            'repository' => $project->getFullName(),
        ]);

        $secretReportPath = $this->localFilesystem->getSecretReportPath($project);

        $result = [
            'success' => $this->runGitleaks($repositoryPath, $secretReportPath),
            'secrets' => false,
            'summary' => false,
        ];
        if (!$result['success']) {
            return $result;
        }

        $report = $this->readSarifReport($secretReportPath);
        $result['secrets'] = $this->getSecrets($report);
        $result['summary'] = $this->getSummary($result['secrets']);

        return $result;
    }

    private function runGitleaks(string $repositoryPath, string $secretReportPath): bool
    {
        $process = new Process([
            'gitleaks',
            'detect',
            '--source', '.',
            '--report-format', 'sarif',
            '--report-path', $secretReportPath,
            '--no-git',
            '--exit-code', '0',
        ]);
        $process->setWorkingDirectory($repositoryPath);
        $process->setTimeout(1200);
        $process->run();

        if (!$process->isSuccessful()) {
            $this->logger->error($process->getErrorOutput());

            return false;
        }

        if (!file_exists($secretReportPath)) {
            return false;
        }

        return true;
    }

    /**
     * Read SARIF report generated by gitleaks.
     *
     * @return array<string,mixed>
     */
    private function readSarifReport(string $secretReportPath): array
    {
        $content = file_get_contents($secretReportPath);
        if (false === $content || '' === trim($content)) {
            return [];
        }

        $report = json_decode($content, true);

        return is_array($report) ? $report : [];
    }

    /**
     * Get findings count per ruleId from a SARIF report.
     *
     * @param array<string,mixed> $report
     *
     * @return array<string,int>
     */
    private function getSecrets(array $report): array
    {
        $secrets = [];
        $results = $report['runs'][0]['results'] ?? [];
        foreach ($results as $finding) {
            $ruleId = isset($finding['ruleId']) ? (string) $finding['ruleId'] : 'unknown';
            $secrets[$ruleId] = isset($secrets[$ruleId]) ? $secrets[$ruleId] + 1 : 1;
        }

        return $secrets;
    }

    /**
     * Get summary (total findings count).
     *
     * @param array<string,int> $secrets
     *
     * @return array<string,int>
     */
    public function getSummary(array $secrets): array
    {
        return [
            'count' => array_sum($secrets),
        ];
    }

    /**
     * Test if gitleaks is available.
     */
    public function isAvailable(): bool
    {
        try {
            $version = $this->getVersion();
            $this->logger->info('[{checker}] gitleaks executable found (version={gitleaks_version})', [
                'checker' => $this->getName(),
                'gitleaks_version' => $version,
            ]);

            return true;
        } catch (\Exception $e) {
            $this->logger->warning('[{checker}] gitleaks not found, scan disabled', [
                'checker' => $this->getName(),
            ]);

            return false;
        }
    }

    /**
     * Get gitleaks version.
     */
    public function getVersion(): string
    {
        $process = new Process(['gitleaks', 'version']);
        $process->run();

        if (!$process->isSuccessful()) {
            throw new ProcessFailedException($process);
        }

        return trim($process->getOutput());
    }
}
